<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
    'AGBase\Module'                    => __DIR__ . '/Module.php',
    'AGBase\Controller\CrudController' => __DIR__ . '/src/AGBase/Controller/CrudController.php',
    'AGBase\Service\AbstractService'   => __DIR__ . '/src/AGBase/Service/AbstractService.php',
    'AGBase\Mail\Mail'                 => __DIR__ . '/src/AGBase/Mail/Mail.php',
);
