<?php
$form = $this->form;
$form->setAttribute('action', $this->url('agacl-admin-roles/default', array('action'=>'edit')));
$form->prepare();
?>

<div class="row">
    
    <div class="col-xs-12 col-sm-8 col-md-6 col-sm-offset-2 col-md-offset-3">
        <?php echo $this->form()->openTag($form); ?>
            <?php echo $this->formHidden($form->get('id')); ?>
            <h2>Papeis <small>Informe os dados a seguir.</small></h2>
            <hr class="colorgraph">
            <div class="form-group">
                <?php echo $this->formRow($form->get('nome')); ?> 
            </div>

            <div class="form-group">
                <label for="parent">Herdar de</label>
                <?php echo $this->formRow($form->get('parent')); ?> 
            </div>
            
            <div class="checkbox">
                <label>
                    <?php echo $this->formRow($form->get('isAdmin')); ?>
                    Administrador ?
                </label>
            </div>

            <hr class="colorgraph">
            <div class="row">
                <div class="col-xs-6 col-md-6">
                    <a href="/admin/acl/roles/" class="btn btn-default btn-block btn-lg">Cancelar</a>
                </div>
                <div class="col-xs-6 col-md-6">
                    <?php echo $this->formSubmit($form->get('submit')); ?>
                </div>
            </div>
        <?php echo $this->form()->closeTag(); ?>
    </div>
</div>