<?php

    $urlPattern = $_SERVER['REQUEST_URI'];

    $formatUrl = function ($page) use ($urlPattern) {

        if (!preg_match('/page/', $urlPattern)) {
            $link = $urlPattern . '/'.$this->controller.'/page/' . (int) $page;
        } else {
            $link = preg_replace('@/page/\d@', '/page/' . (int) $page, $urlPattern);
        }
        
        $return = str_replace('///', '/', $link);
        $return = str_replace('//', '/', $return);
        return $return;
    };

?>

<?php if ($this->pageCount): ?>
    <div class="text-center">
        
        <pre>Barra de Navegação: EM PARTIALS USERS<br/><?php echo $urlPattern ?></pre>
        <pre><?php echo $formatUrl($page); ?></pre>
        
        <ul class="pagination pagination-centered">
            <?php if (isset($this->previous)): ?>
                <li><a href="<?php echo $formatUrl(1); ?>">«</a></li>
            <?php else: ?>
                <li class="disabled"><a href="#">«</a></li>
            <?php endif; ?>

            <?php foreach ($this->pagesInRange as $page): ?>
                <?php if ($page != $this->current): ?>
                    <li>
                        <a href="<?php echo $formatUrl($page); ?>"><?php echo $page; ?></a>
                    </li>                
                <?php else: ?>
                    <li class="active">
                        <a href="#"><?php echo $page; ?></a>
                    </li>                
                <?php endif; ?>
            <?php endforeach; ?>

            <?php if (isset($this->next)): ?>
                <li><a href="<?php echo $formatUrl($this->last); ?>">»</a></li>
            <?php else: ?>
                <li class="disabled"><a href="#">»</a></li>
            <?php endif; ?>
        </ul>
    </div>
<?php endif; ?>