
<?php
$form = $this->form;
$controllerAndAction = array('controller' => 'users', 'action' => 'address');
$form->setAttribute('action', $this->url('aguser-admin/default', $controllerAndAction));
$form->prepare();
?>

<?php echo $this->form()->openTag($form); ?>

<div class="" id="address">

    <span class="entry-title">
        <h5><span>Endereço <small>Informe os dados a seguir.</small></span></h5>
    </span>    

    <?php echo $this->formHidden($form->get('id')); ?>
    <?php echo $this->formHidden($form->get('security')); ?> 

    <p class="form-row">
        <label for="Logradouro" class="">Logradouro: <span class="required">*</span></label>
        <?php echo $this->formRow($form->get('logradouro')); ?> 
    </p>  
    
    <div class="clear"></div>
    
    <p class="form-row">
        <label for="Complemento" class="">Complemento: </label>
        <?php echo $this->formRow($form->get('complemento')); ?> 
    </p>
    
    <div class="clear"></div>
    
    <p class="form-row form-row-first">
        <label for="Numero" class="">Número: </label>
        <?php echo $this->formRow($form->get('numero')); ?>
    </p>     
    
    <p class="form-row form-row-last">
        <label for="Cep" class="">CEP: <span class="required">*</span></label>
        <?php echo $this->formRow($form->get('cep')); ?> 
    </p>        

    <div class="clear"></div>
    
    <p class="form-row ">
        <label for="Bairro" class="">Bairro: <span class="required">*</span></label>
        <?php echo $this->formRow($form->get('bairro')); ?>
    </p>     
    
    <div class="clear"></div>
    
    <p class="form-row">
        <label for="Cidade" class="">Cidade: <span class="required">*</span></label>
        <?php echo $this->formRow($form->get('cidade')); ?> 
    </p>      
    
    <div class="clear"></div>
    
    <p class="form-row">
        <label for="Estado" class="">Estado: <span class="required">*</span></label>
        <?php echo $this->formRow($form->get('estado')); ?>
    </p>     

    <div class="clear"></div>

    <p class="form-row">
        <a href="<?php echo $this->url('aguser-admin/default', array('controller' => 'users', 'action' => 'index')); ?>" class="button cancel">Cancelar</a>
        <?php echo $this->formSubmit($form->get('submit')); ?>
    </p>        

</div>

<?php echo $this->form()->closeTag(); ?>

