<h1><?php echo $this->controller; ?></h1>

<br />

<p>
    <a class="btn btn-success" href="<?php echo $this->url('aguser-admin/default',array('action'=>'new')); ?>">Novo</a>
</p>

<table class="table">
    <tr>
        <th>ID</th>
        <th>Nome</th>
        <th>Email</th>
        <th>Papel</th>
        <th>Ação</th>
    </tr>
    
    <?php foreach($this->data as $entity): ?>
    <tr>
    
        <td><?php echo $entity->getId(); ?></td>
        <td><?php echo $entity->getNome(); ?></td>
        <td><?php echo $entity->getEmail(); ?></td>
        <td><?php echo $entity->getRole(); ?></td>
        <td>
            <a class="btn btn-default" href="<?php echo $this->url('aguser-admin/default',
                    array('controller'=>'users','action'=>'edit','id'=>$entity->getId()));?>">Editar</a>
            
            <a class="btn btn-danger" href="<?php echo $this->url('aguser-admin/default',
                    array('controller'=>'users','action'=>'delete','id'=>$entity->getId()));?>">Delete</a>
            
        </td>
    </tr>
    <?php endforeach; ?>
</table>
<br />

<?php 

echo $this->paginationControl($this->data,'Sliding','partials/paginator', array('controller' => $this->controller)); 

$this->headScript()->captureStart(); 

?>

$(function(){
    // variável para conter a url deletar
    var url_deletar     = '<?php echo $this->url('aguser-admin/default', array("controller" => $this->controller, "action" => "delete")); ?>' + '/';
 
    // qualquer link que tiver a url deletar vai sofrer um evento quando for clicada
    $("a[href*='" + url_deletar + "']").click(function (event) {
        // variável contendo o id referente ao botão clicado
        var contato_id  = $(this).attr('href').split(url_deletar).pop();
        // variável contendo mensagem da janela
        var mensagem = "Deseja realmente apagar o registro de ID " + contato_id + "?";
        // variável com resposta da mensagem colocada na janela
        var confirmacao = confirm(mensagem);
 
        // se a confirmação for false o fluxo é interrompido
        if (!confirmacao)
            // elimar o evendo do botão clicado
            event.preventDefault();
    });
});

<?php 

$this->headScript()->captureEnd(); 