<?php echo $this->doctype(); ?>

<html lang="pt-BR" class="js no-touch rgba boxsizing csstransforms csstransforms3d csstransitions">
    <head>
        <meta charset="UTF-8">
        <!--<meta name="robots" content="index, follow">-->

        <meta name="keywords" content="">
        <meta name="description" content="">
        <title>JackModaIntima</title>

        <!-- mobile setting -->
        <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">

        <!-- Le styles -->
        <?php
        echo $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/favicon.ico'))
                ->prependStylesheet($this->basePath() . '/theme/css/frontend.css')
//            ->prependStylesheet($this->basePath() . '/theme/css/fancybox.css') 
//            ->prependStylesheet($this->basePath() . '/theme/css/ui.css') 
//            ->prependStylesheet($this->basePath() . '/theme/css/bbpress.css') 
//            ->prependStylesheet($this->basePath() . '/theme/css/bbpress(1).css') 
                ->prependStylesheet($this->basePath() . '/css/style.css')
                ->prependStylesheet($this->basePath() . '/css/bootstrap-theme.min.css')
                ->prependStylesheet($this->basePath() . '/css/bootstrap.min.css')
//            ->prependStylesheet($this->basePath() . '/theme/css/bbpress(2).css')
//            ->prependStylesheet($this->basePath() . '/theme/css/main-blue.css')
//            ->prependStylesheet($this->basePath() . '/theme/css/grid.css')
//            ->prependStylesheet($this->basePath() . '/theme/css/flexslider.css')
        ?>

        <!-- add css stylesheets -->	
        <link rel="stylesheet" href="/theme/css/bbpress(2).css" type="text/css" media="screen">
        <link rel="stylesheet" href="/theme/css/main-blue.css" type="text/css" media="screen">
        <link rel="stylesheet" href="/theme/css/grid.css" type="text/css" media="screen">
        <!--<link rel="stylesheet" href="/theme/css/flexslider.css" type="text/css" media="screen">-->
        <link rel="stylesheet" href="/theme/css/wmuslider.css" type="text/css" media="screen">
        <link rel="stylesheet" href="/theme/css/jquery.fancybox-1.3.4.css" type="text/css" media="screen">        

        <!-- Scripts / jquery -->
        <?php
        echo $this->headScript()
                ->prependFile($this->basePath() . '/theme/js/jquery.preloader.js')
                ->prependFile($this->basePath() . '/theme/js/scripts.js')
                ->prependFile($this->basePath() . '/js/jquery.min.js')
                ->prependFile($this->basePath() . '/js/bootstrap.min.js')
                ->prependFile($this->basePath() . '/theme/js/jquery(1).js')
                ->prependFile($this->basePath() . '/theme/js/jquery.fancybox-1.3.4.pack.js')
                ->prependFile($this->basePath() . '/theme/js/jquery-ui-1.9.2.min.js')
                ->prependFile($this->basePath() . '/theme/js/jigoshop_frontend.js')
                ->prependFile($this->basePath() . '/theme/js/script.js')
                ->prependFile($this->basePath() . '/theme/js/jquery(1).js')
                ->prependFile($this->basePath() . '/theme/js/jquery.fancybox-1.3.4.pack.js')
                ->prependFile($this->basePath() . '/theme/js/jquery-ui-1.9.2.min.js')
                ->prependFile($this->basePath() . '/theme/js/blockui.js')
                ->prependFile($this->basePath() . '/theme/js/jigoshop_frontend.js')
                ->prependFile($this->basePath() . '/js/respond.min.js', 'text/javascript', array('conditional' => 'lt IE 9',))
                ->prependFile($this->basePath() . '/js/html5shiv.js', 'text/javascript', array('conditional' => 'lt IE 9',))
        ;
        ?> 

        <?php
        $rota = array();
        $route = $this->RouterHelper();
        if ($route):
            $rota['nome'] = $route->getMatchedRouteName();
            $rota['params'] = $route->getParams();
        endif;
        $onuser = $this->UserIdentity("AGUser");
        if ($onuser):
            $u = $onuser->getId();
        endif;
        ?>         

        <?php // Zend\Debug\Debug::dump($u); die; ?>

        <style type="text/css">
            .recentcomments a{
                display:inline !important;
                padding:0 !important;
                margin:0 !important;
            }
        </style>

        <!-- fancy box -->
        <!--<script type="text/javascript" src="/theme/js/jquery.fancybox-1.3.4.pack(1).js"></script>-->
        <!--<script type="text/javascript" src="/theme/js/jquery.mousewheel-3.0.4.pack.js"></script>-->
        <!--easing--> 
       <!--<script type="text/javascript" src="/theme/js/jquery.easing.1.3.js"></script>-->
        <!--Tabs--> 
       <!--<script type="text/javascript" src="/theme/js/jquery.tools.min.js"></script>-->
        <!--custom script--> 
        <!--<script type="text/javascript" src="/theme/js/scripts.js"></script>-->
        <!--quote rotator--> 
       <!--<script type="text/javascript" src="/theme/js/jquery.quovolver.js"></script>-->
        <!--wmuSlider--> 
       <!--<script type="text/javascript" src="/theme/js/modernizr.custom.min.js"></script>-->
        <!--FlexiSlider--> 
        <!--<script type="text/javascript" src="/theme/js/jquery.flexslider.js"></script>--> 
        <!--Twitter--> 
       <!--<script type="text/javascript" src="/theme/js/twitter.js"></script>-->
        <!--isotope-->  
       <!--<script type="text/javascript" src="/theme/js/jquery.isotope.min.js"></script>-->
        <!--image preloader-->  
        <!--<script type="text/javascript" src="/theme/js/jquery.preloader.js"></script>-->

        <!-- Google map -->
<!--        <script src="/theme/js/js" type="text/javascript"></script>
        <script src="/theme/js/main.js"></script>-->
        <!-- google webfont font replacement -->
        <!--<link href="/theme/css/css" rel="stylesheet" type="text/css">-->

        <style type="text/css">
            #content { background: #292929 url("/theme/images/diagmonds.png"); }					
        </style>

        <!--[if lte IE 6]>
            <style>#top, #bottom, #left, #right { display: none; }</style>
        <![endif]-->

<!--        <script type="text/javascript" charset="UTF-8" src="/theme/js/common.js"></script>
        <script type="text/javascript" charset="UTF-8" src="/theme/js/util.js"></script>
        <script type="text/javascript" charset="UTF-8" src="/theme/js/stats.js"></script>-->
    </head>

    <body id="top" class="home page page-id-425 page-parent page-template page-template-template-full-width-php">

        <div id="content">
            <!-- Main Header -->
            <header id="main-header">
                <!-- Tob Bar Container -->
                <div class="container_wrap" id="top-bar">
                    <div class="container">

                        <div class="eight columns alignleft">
                            <div class="top-info">
                                <!-- Search form -->
                                <form method="get" id="search_block" action="" class="">
                                    <div>
                                        <label for="search_field_block"></label>
                                        <!-- end auto clear label -->
                                        <input type="text" name="s" id="search_field_block" placeholder="O que procura?">
                                        <!-- end search field -->
                                        <input type="submit" id="search_submit_block" value="Buscar">
                                        <input type="hidden" name="post_type" value="product">
                                    </div>	
                                    <!-- end search submit -->
                                </form>
                                <!-- end search form -->
                                <span>
                                    <a href="" class="button">
                                        0 itens - R$ 0,00
                                    </a>
                                </span>
                                <span>Fone: +55 84 87101116</span>
                            </div>
                        </div>
                        <div class="four columns alignright">
                            <span class="social_bookmarks">
                                <!--<img src="<?php // echo $this->basePath($this->Avatar($u));  ?>" class="img-circle" height="25" width="25"> <span class="caret"></span>-->

                                <?php if ($onuser): ?>
                                    <a href="<?php echo $this->url('aguser-logout'); ?>">Sair</a>
                                    <?php echo $u; ?>
                                <?php else: ?>
                                    Bem vindo(a), <a href="<?php echo $this->url('aguser-register'); ?>">cadastre-se</a> ou faça <a href="<?php echo $this->url('aguser-auth'); ?>">login.</a>
                                <?php endif; ?>

                            </span>
                        </div>
                    </div>
                </div>
                <!-- End Tob Bar Container -->

                <!-- Head Container -->
                <div class="container_wrap" id="header">
                    <div class="container">
                        <nav class="navbar navbar-inverse" role="navigation">
                            <div class="container-fluid">
                                <!-- Brand and toggle get grouped for better mobile display -->
                                <div class="navbar-header">
                                    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
                                        <span class="sr-only">Navegação</span>
                                        <span class="icon-bar"></span>
                                        <span class="icon-bar"></span>
                                        <span class="icon-bar"></span>
                                    </button>
                                    <h1 class="">
                                        <a href="/">
                                            <img src="/theme/images/jack.png" alt="Logo" width="120">
                                        </a>
                                    </h1>
                                </div>
                                <!-- Collect the nav links, forms, and other content for toggling -->
                                <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                                    <ul class="nav navbar-nav">
                                        <li class=""><a href="/">Loja</a></li>
                                        <li class="dropdown">
                                            <a href="#" class="dropdown-toggle" data-toggle="dropdown">Carrinho <span class="caret"></span></a>
                                            <ul class="dropdown-menu" role="menu">
                                                <li><a href="#">Efetuar Pagamento</a></li>
                                                <li class="divider"></li>
                                                <li><a href="#">Exibir Compras</a></li>
                                                <li class="divider"></li>
                                                <li><a href="#">Mais Opções...</a></li>
                                            </ul>
                                        </li>
                                    </ul>

                                    <ul class="nav navbar-nav navbar-right">
                                        <li class="dropdown">
                                            <a href="#" class="dropdown-toggle" data-toggle="dropdown">Minha Conta <span class="caret"></span></a>
                                            <ul class="dropdown-menu" role="menu">

                                                <?php if ($onuser): ?>
                                                    <li><a href="<?php echo $this->url('aguser-logout'); ?>">Fazer Logout</a></li>
                                                <?php else: ?>
                                                    <li><a href="<?php echo $this->url('aguser-auth'); ?>">Fazer Login</a></li>
                                                <?php endif; ?>  

                                                <?php if ($onuser): ?>
                                                    <li class="divider"></li>
                                                    <li><a href="<?php echo $this->url('aguser-admin/default', array('controller' => 'users', 'action' => 'address')); ?>">Endereço...</a></li>
                                                    <li><a href="<?php echo $this->url('aguser-admin/default', array('controller' => 'users', 'action' => 'edit', 'id' => $this->UserIdentity("AGUser")->getId())); ?>">Alterar Senha...</a></li>
                                                    <li><a href="<?php echo $this->url('aguser-admin/upload'); ?>">Imagem do Usuário...</a></li>                                                    
                                                    <li class="divider"></li>
                                                    <li><a href="<?php echo $this->url('aguser-admin/default', array('controller' => 'users', 'action' => 'index')); ?>">Meu Ambiente...</a></li>
                                                <?php endif; ?> 
                                            </ul>
                                        </li>
                                    </ul>
                                </div><!-- /.navbar-collapse -->
                            </div><!-- /.container-fluid -->
                        </nav> 
                    </div>
                </div>
                <!-- End Head Container --><!-- this is index.php -->

                <?php if ($rota['nome'] == 'home'): ?>
                    <!-- Page Title Container -->
                    <div class="container_wrap" id="slogan">
                        <div class="container">
                            <div class="full">
                                <h4>"O entusiasmo é a maior força da alma. <br/>
                                    Conserva-o e nunca te faltará poder para conseguires o que desejas."</h4>
                            </div>
                        </div>	
                    </div>
                    <!-- End Page Title Container -->

                    <!-- flexSlider Container -->
                    <div class="container_wrap" id="slideshow_big">
                        <!-- start header -->
                        <!--                        <div class="container" style="position:relative; z-index:2;">
                                                    <div class="flexslider">
                                                        <ul class="slides">
                                                            <li style="width: 100%; float: left; margin-right: -100%; display: list-item;">
                                                                <img width="930" height="310" src="/theme/images/modelo1.png" class="attachment-header_image wp-post-image" alt="woman">
                                                                 Do stuff with empty posts (or leave blank to skip empty posts) 
                                                            </li>
                                                            <li style="width: 100%; float: left; margin-right: -100%; display: none;">
                                                                <img width="930" height="310" src="/theme/images/modelo2.png" class="attachment-header_image wp-post-image" alt="man">
                                                                 Do stuff with empty posts (or leave blank to skip empty posts) 
                                                            </li>
                                                        </ul>
                                                        <ol class="flex-control-nav">
                                                            <li><a class="active">1</a></li>
                                                            <li><a class="">2</a></li>
                                                        </ol>
                                                        <ul class="flex-direction-nav">
                                                            <li><a class="prev" href="http://alexgurghis.com/themes/zeux-ecommerce/#">Previous</a></li>
                                                            <li><a class="next" href="http://alexgurghis.com/themes/zeux-ecommerce/#">Next</a></li>
                                                        </ul>
                                                    </div>
                                                </div>-->
                        <!-- end header -->
                        <div class="container">                        
                            <div id="carousel-example-generic" class="carousel slide" data-ride="carousel">
                                <!-- Indicators -->
                                <ol class="carousel-indicators">
                                    <li data-target="#carousel-example-generic" data-slide-to="0" class="active"></li>
                                    <li data-target="#carousel-example-generic" data-slide-to="1"></li>
                                </ol>

                                <!-- Wrapper for slides -->
                                <div class="carousel-inner">
                                    <div class="item active">
                                        <img src="/theme/images/modelo1.png" height="100%" width="100%">
                                        <div class="carousel-caption">
                                        </div>
                                    </div>
                                    <div class="item">
                                        <img src="/theme/images/modelo2.png" height="100%" width="100%">
                                        <div class="carousel-caption">
                                        </div>
                                    </div>
                                </div>

                                <!-- Controls -->
                                <a class="left carousel-control" href="#carousel-example-generic" role="button" data-slide="prev">
                                    <span class="glyphicon glyphicon-chevron-left"></span>
                                </a>
                                <a class="right carousel-control" href="#carousel-example-generic" role="button" data-slide="next">
                                    <span class="glyphicon glyphicon-chevron-right"></span>
                                </a>
                            </div>                        
                        </div>                        
                    </div>
                    <!-- End flexSlider Container -->
                <?php endif; ?>

                <div class="container">
                    <?php echo $this->message(); ?>
                </div>
            </header>
            <!-- End Main Header -->

            <!-- Main Container -->
            <section id="main-content">
                <!-- Container -->
                <div id="container">
                    <div id="main-wrapper" class="container">

                        <?php echo $this->content; ?>

                        <div class="clear"></div>

                        <div class="container partners">
                            <span class="entry-title">
                                <h5><span>Marcas</span></h5>
                            </span>
                            <div class="one_fifth first column_container">
                                <a class="partners_images" href="http://alexgurghis.com/themes/zeux-ecommerce/#"><img src="/theme/images/dribbble1.png" alt="" style="opacity: 0.5;"></a>
                            </div>
                            <div class="one_fifth column_container">
                                <a class="partners_images" href="http://alexgurghis.com/themes/zeux-ecommerce/#"><img src="/theme/images/google.png" alt="" style="opacity: 0.5;"></a>
                            </div>
                            <div class="one_fifth column_container">
                                <a class="partners_images" href="http://alexgurghis.com/themes/zeux-ecommerce/#"><img src="/theme/images/smashing.png" alt="" style="opacity: 0.5;"></a>
                            </div>
                            <div class="one_fifth column_container">
                                <a class="partners_images" href="http://alexgurghis.com/themes/zeux-ecommerce/#"><img src="/theme/images/android.png" alt="" style="opacity: 0.5;"></a>
                            </div>
                            <div class="one_fifth column_container">
                                <a class="partners_images" href="http://alexgurghis.com/themes/zeux-ecommerce/#"><img src="/theme/images/dribbble.png" alt="" style="opacity: 0.5;"></a>
                            </div>
                        </div>
                    </div>

                    <!-- Footer Container -->
                    <footer class="container_wrap" id="footer">

                        <!-- Begin Footer -->
                        <div class="container">

                            <div class="one_fourth first column_container">
                                <div class="widget">
                                    <div class="widget-title">Links Rápidos</div>
                                    <div class="menu-sidebar-container">
                                        <ul id="menu-sidebar" class="menu">
                                            <li id="menu-item-448" class="menu-item menu-item-type-post_type menu-item-object-page current-menu-item page_item page-item-425 current_page_item menu-item-448">
                                                <a href="/">Home</a>
                                            </li>
                                            <li id="menu-item-449" class="menu-item menu-item-type-post_type menu-item-object-page menu-item-449">
                                                <a href="http://alexgurghis.com/themes/zeux-ecommerce/template-pages/about-us/">About Us</a>
                                            </li>
                                            <li id="menu-item-450" class="menu-item menu-item-type-post_type menu-item-object-page menu-item-450">
                                                <a href="http://alexgurghis.com/themes/zeux-ecommerce/template-pages/our-services/">Our Services</a>
                                            </li>
                                            <li id="menu-item-451" class="menu-item menu-item-type-post_type menu-item-object-page menu-item-451">
                                                <a href="http://alexgurghis.com/themes/zeux-ecommerce/template-pages/our-team/">Our Team</a>
                                            </li>
                                        </ul>
                                    </div>
                                </div>						
                            </div>	

                            <div class="one_fourth column_container">
                                <div class="widget">
                                    <div class="widget-title">Novidades</div>
                                    <ul>
                                        <li class="news-content">
                                            <a class="news-link" title="" href="http://alexgurghis.com/themes/zeux-ecommerce/2012/06/praesent-facilisis-diam-nec/">
                                                <strong class="news-headline">Praesent facilisis diam nec<span class="news-time">June 11th, 2012</span></strong>
                                            </a>
                                        </li>
                                        <li class="news-content">
                                            <a class="news-link" title="" href="http://alexgurghis.com/themes/zeux-ecommerce/2012/06/ut-elementum-lorem-sed-elit/">
                                                <strong class="news-headline">Ut elementum lorem sed elit<span class="news-time">June 11th, 2012</span></strong>
                                            </a>
                                        </li>
                                        <li class="news-content">
                                            <a class="news-link" title="" href="http://alexgurghis.com/themes/zeux-ecommerce/2012/06/link-title/">
                                                <strong class="news-headline">Link Title<span class="news-time">June 11th, 2012</span></strong>
                                            </a>
                                        </li>
                                    </ul>
                                </div>						
                            </div>

                            <div class="one_fourth column_container">
                                <div class="widget">
                                    <div class="widget-title">Latest Tweets</div>	
                                    <ul class="twitterbox" id="twitter_update_list_wpcrown_custom_twitter-2">
                                        <li class="news-content">
                                            <div class="twitter-feed-content">
                                                <strong class="twitter-headline">
                                                    <span class="twittext"></span><p></p>
                                                    <span class="twittime"><i class="icon-twitter"></i>
                                                        <a target="_blank" class="time" href="https://twitter.com/agurghis/status/">45 years&nbsp;ago</a>
                                                    </span>
                                                </strong>
                                            </div>
                                        </li>
                                        <a target="_blank" class="time" href="https://twitter.com/agurghis/status/"></a>
                                        <li class="followme">
                                            <a target="_blank" class="time" href="https://twitter.com/agurghis/status/"></a>
                                            <a style="font-weight: normal; letter-spacing: normal; font-size: 11px;" href="https://twitter.com/agurghis">Joine <br>

                                                <b>Warning</b>:  number_format() expects parameter 1 to be double, string given in <b>/nfs/c08/h03/mnt/126636/domains/alexgurghis.com/html/themes/zeux-ecommerce/wp-content/themes/Zeux-e-Commerce/functions.php</b> on line <b>202</b><br>

                                                Followers @agurghis</a>
                                        </li>
                                    </ul>
                                </div>						
                            </div>

                            <div class="one_fourth column_container">

                                <div class="widgetflickr widget">
                                    <div class="widget-title">Flickr Stream</div>
                                    <div class="widget-content">
                                        <ul id="flickr_widget">
                                            <li><a class="flickr_images image" href="http://farm9.staticflickr.com/8062/8181530604_04f9b14b74_b.jpg" title="SuperNova">
                                                    <img src="/theme/images/8181530604_04f9b14b74_s.jpg" alt="" style="opacity: 1;">
                                                </a>
                                            </li>
                                            <li>
                                                <a class="flickr_images image" href="http://farm8.staticflickr.com/7063/7023527639_8426fb2bf5_b.jpg" title="Prometheus – A Responsive e-Commerce Theme">
                                                    <img src="/theme/images/7023527639_8426fb2bf5_s.jpg" alt="" style="opacity: 1;">
                                                </a>
                                            </li>
                                            <li>
                                                <a class="flickr_images image" href="http://farm7.staticflickr.com/6191/6148972167_46cb20106d_b.jpg" title="Reading">
                                                    <img src="/theme/images/6148972167_46cb20106d_s.jpg" alt="" style="opacity: 1;">
                                                </a>
                                            </li>
                                            <li>
                                                <a class="flickr_images image" href="http://farm6.staticflickr.com/5248/5233469529_d9e8725af9_b.jpg" title="Beautiful winter">
                                                    <img src="/theme/images/5233469529_d9e8725af9_s.jpg" alt="" style="opacity: 1;">
                                                </a>
                                            </li>
                                            <li>
                                                <a class="flickr_images image" href="http://farm5.staticflickr.com/4089/5173817347_3ee69ba374_b.jpg" title="Yosemite National Park">
                                                    <img src="/theme/images/5173817347_3ee69ba374_s.jpg" alt="" style="opacity: 1;">
                                                </a>
                                            </li>
                                            <li>
                                                <a class="flickr_images image" href="http://farm5.staticflickr.com/4084/5173295868_6a2d08f8d1_b.jpg" title="www.alexgurghis.com">
                                                    <img src="/theme/images/5173295868_6a2d08f8d1_s.jpg" alt="" style="opacity: 1;">
                                                </a>
                                            </li>
                                        </ul>
                                        <p>
                                            <span class="follow-twitter">
                                                <a href="http://www.flickr.com/photos/73818667@N00/">View More +</a>
                                            </span>
                                        </p>
                                        <p></p>
                                    </div>
                                </div>						
                            </div>
                        </div>
                        <!-- End Footer -->
                    </footer>
                    <!-- End Footer Container -->

                    <!-- Socket Container -->
                    <div class="container_wrap" id="socket">
                        <!-- Begin Copyright -->
                        <div class="container">
                            @ Copyright - <a href="/ThemeSite.html">Zeux - A responsive &amp; super flexible e-commerce theme</a> - by <a href="http://www.alexgurghis.com/">AlexGurghis.com						
                            </a><div class="backtop"><a href="http://www.alexgurghis.com/">
                                </a><a href="http://alexgurghis.com/themes/zeux-ecommerce/#backtop">Top</a>
                            </div>
                        </div>
                        <!-- End Copyright -->
                    </div>
                    <!-- End Socket Container -->
                </div>
                <!-- End Container -->
            </section>	
            <!-- End Main Container -->
        </div>

        <!--<script src="/theme/js/jquery.wmuslider-min.js"></script>-->
<!--        <script>
            jQuery('.wmuSlider').wmuSlider({
                touch: Modernizr.touch,
                animation: 'slide',
                items: 2
            });
        </script>	-->

<!--
        <div id="fancybox-tmp">
        </div>
        <div id="fancybox-loading">
            <div>
            </div>
        </div>
        <div id="fancybox-overlay">
        </div>-->

        <?php echo $this->inlineScript() ?>
    </body>
</html>