
<?php
$form = $this->form; 
$form->setAttribute('action', $this->url('agacl-admin-resources/default',array('action'=>'new')));
$form->prepare();
?>

<div class="row">
    <div class="col-xs-12 col-sm-8 col-md-6 col-sm-offset-2 col-md-offset-3">
        <?php echo $this->form()->openTag($form); ?>
            <?php echo $this->formHidden($form->get('id')); ?>
            <h2>Código <small>Informe o nome do módulo.</small></h2>
            <hr class="colorgraph">
            <div class="form-group">
                <?php echo $this->formRow($form->get('nome')); ?> 
            </div>
            <hr class="colorgraph">
            <div class="row">
                <div class="col-xs-6 col-md-6">
                    <a href="<?php echo $this->url('agacl-admin-resources/default',array('action'=>'index')); ?>" class="btn btn-default btn-block btn-lg">Cancelar</a>
                </div>
                <div class="col-xs-6 col-md-6">
                    <?php echo $this->formSubmit($form->get('submit')); ?>
                </div>
            </div>
        <?php echo $this->form()->closeTag(); ?>
    </div>
</div>