<?php echo $this->doctype(); ?>

<html lang="pt-br">
    <head>
        <meta charset="utf-8">
        <?php echo $this->headTitle('ZF2 '.('Skeleton Application'))->setSeparator(' - ')->setAutoEscape(false) ?>

        <?php echo $this->headMeta()
            ->appendName('viewport', 'width=device-width, initial-scale=1.0')
            ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
        ?>

        <!-- Le styles -->
        <?php echo $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/favicon.ico'))
                        ->prependStylesheet($this->basePath() . '/css/style.css')
                        ->prependStylesheet($this->basePath() . '/css/bootstrap-theme.min.css')
                        ->prependStylesheet($this->basePath() . '/css/bootstrap.min.css') ?>

        <!-- Scripts -->
        <?php echo $this->headScript()
            ->prependFile($this->basePath() . '/js/bootstrap.min.js')
            ->prependFile($this->basePath() . '/js/jquery.min.js')
            ->prependFile($this->basePath() . '/js/respond.min.js', 'text/javascript', array('conditional' => 'lt IE 9',))
            ->prependFile($this->basePath() . '/js/html5shiv.js',   'text/javascript', array('conditional' => 'lt IE 9',))
        ; ?>

    </head>
    <body>
        <nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
            <div class="container">
                <div class="navbar-header">
                    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>
                    <a class="navbar-brand" href="<?php echo $this->url('home') ?>"><img src="<?php echo $this->basePath('img/zf2-logo.png') ?>" alt="Zend Framework 2"/>&nbsp;<?php echo('Skeleton Application') ?></a>
                </div>
                <div class="collapse navbar-collapse">
                    <ul class="nav navbar-nav">
                        <?php $url_home = $this->url('aguser-admin/default'); ?>
                        <li <?php echo $this->MenuHelperActive($url_home); ?> >
                            <a href="<?php echo $url_home; ?>">Início</a>
                        </li>                         
                    </ul>
                    
                    <?php $onuser = $this->UserIdentity("AGUser"); ?>
                    
                    <ul class="nav navbar-nav navbar-right">
                        
                        <?php if($onuser): ?>
                            <?php $url_logout = $this->url('aguser-logout'); ?>
                            <li <?php echo $this->MenuHelperActive($url_logout); ?> >
                                <a href="<?php echo $url_logout; ?>">
                                    <?php echo $this->UserIdentity("AGUser")->getNome(); ?> (Sair)
                                </a>
                            </li>                         
                        <?php else: ?>
                            <?php $url_auth = $this->url('aguser-auth'); ?>
                            <li <?php echo $this->MenuHelperActive($url_auth); ?> >
                                <a href="<?php echo $url_auth; ?>">Acessar</a>
                            </li>                             
                        <?php endif; ?>                         

                        <?php if($onuser): ?>
                        <li class="dropdown">
                            <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                                <!--<img src="<?php // echo $this->basePath($this->Avatar($this->UserIdentity("AGUser")->getId())); ?>" class="img-circle" height="25" width="25"> <span class="caret"></span>-->
                            </a>
                            <ul class="dropdown-menu" role="menu">
                                <li><a href="<?php echo $this->url('aguser-admin/default', array('controller'=>'users','action'=>'address'));?>">Endereço...</a></li>
                                <li><a href="<?php echo $this->url('aguser-admin/default', array('controller'=>'users','action'=>'edit','id'=>$this->UserIdentity("AGUser")->getId()));?>">Alterar Senha...</a></li>
                                <li><a href="<?php echo $this->url('aguser-admin/upload'); ?>">Imagem do Usuário...</a></li>
                                <li class="divider"></li>
                                <li><a href="<?php echo $this->url('aguser-logout'); ?>">Sair</a></li>
                            </ul>
                        </li>
                        <?php endif; ?> 
                    </ul> 
                </div><!--/.nav-collapse -->
            </div>
        </nav>
        
        <?php $rota  = array(); ?>
        <?php $route = $this->RouterHelper(); ?>
        <?php if($route): ?>
            <?php $rota['nome']   = $route->getMatchedRouteName(); ?>
            <?php $rota['params'] = $route->getParams(); ?>
        <?php endif; ?>

        <pre>
            <?php print_r($route); ?>
        </pre>
        
        <div class="container">
            
            <?php if($rota['params']['__NAMESPACE__'] == 'AGAcl\Controller'): ?>
                <nav class="navbar navbar-default">
                  <div class="container-fluid">
                    <div class="navbar-header">
                      <a class="navbar-brand" href="#">Lista de Açõe Controladas</a>
                    </div>
                    <div>
                        
                        <?php list($rt, $sr) = explode("/", $rota['nome']); ?>
                        
                        <ul class="nav navbar-nav">
                            <?php $url_resources = $this->url('agacl-admin-resources/default',array('action'=>'index')); ?>
                            <li <?php echo $this->MenuHelperActive($url_resources); ?> >
                                <a href="<?php echo $url_resources; ?>">Módulos</a>
                            </li>           
                            <?php $url_papel = $this->url('agacl-admin-roles/default'); ?>
                            <li <?php echo $this->MenuHelperActive($url_papel); ?> >
                                <a href="<?php echo $url_papel; ?>">Papeis</a>
                            </li>           
                            <?php $url_privileges = $this->url('agacl-admin-privileges/default',array('action'=>'index')); ?>
                            <li <?php echo $this->MenuHelperActive($url_privileges); ?> >
                                <a href="<?php echo $url_privileges; ?>">Privilégios</a>
                            </li>           
                        </ul>
                    </div>
                  </div>
                </nav>        
            <?php endif; ?>             
            
            <?php echo $this->message(); ?>
            <?php echo $this->content; ?>
            <hr>
            <footer>
                <p>&copy; 2005 - <?php echo date('Y') ?> by Zend Technologies Ltd. <?php echo('All rights reserved.') ?></p>
            </footer>
        </div> <!-- /container -->
        <?php echo $this->inlineScript() ?>
    </body>
</html>
