
<?php
$form = $this->form;
$form->setAttribute('action', $this->url('aguser-auth'));
$form->prepare();
?>

<div class="row">
    <div class="col-sm-6 col-md-4 col-md-offset-4">
        <div class="account-wall">
            <div class="form-group text-center">
                <img class="profile-img" src="<?php echo $this->basePath('img/photo.png') ?>" alt="">
            </div>
            <?php echo $this->form()->openTag($form); ?>

            <?php if ($this->error): ?>

                <div class="alert alert-danger alert-dismissible" role="alert">
                    <button type="button" class="close" data-dismiss="alert"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
                    <ul>
                        <li class="active">Usuário ou senha inválidos.</li>
                    </ul>
                </div>            

            <?php endif; ?>             

            <div class="form-group">
                <?php echo $this->formRow($form->get('email')); ?> 
            </div>
            <div class="form-group">
                <?php echo $this->formRow($form->get('password')); ?> 
            </div>
            <div class="form-group">
                <?php echo $this->formSubmit($form->get('submit')); ?>
            </div>
            <a href="<?php echo $this->url('aguser-auth/ajuda'); ?>" class="pull-right need-help">Ajuda? </a><span class="clearfix"></span>
            <?php echo $this->form()->closeTag(); ?>
        </div>
    </div>
</div>

