<?php
$form = $this->form;
$form->setAttribute('action',$this->url('aguser-auth/remember'));
$form->prepare();
?>

<div class="row">
    <div class="col-xs-12 col-sm-8 col-md-6 col-sm-offset-2 col-md-offset-3">
        <?php echo $this->form()->openTag($form); ?>
            <?php echo $this->formHidden($form->get('id')); ?>
            <?php echo $this->formHidden($form->get('security')); ?>
            <h2>Atualização de senha <small></small></h2>
            <hr class="colorgraph">
            <div class="form-group">
                <?php echo $this->formRow($form->get('password')); ?> 
            </div>
            <div class="form-group">
                <?php echo $this->formRow($form->get('confirmation')); ?>
            </div>
            <hr class="colorgraph">
            <div class="row">
                <div class="col-xs-6 col-md-6">
                    <a href="<?php echo $this->url('aguser-auth'); ?>" class="btn btn-default btn-block btn-lg">Cancelar</a>
                </div>
                <div class="col-xs-6 col-md-6">
                    <?php echo $this->formSubmit($form->get('submit')); ?>
                </div>
            </div>
        <?php echo $this->form()->closeTag(); ?>
    </div>
</div>