<div class="entry-title">
    <h5><span>Últimas <strong>Novidades</strong></span></h5>
</div>

<ul class="products">

    <li class="product first">
        <a href="http://alexgurghis.com/themes/zeux-ecommerce/product/wool-blended-jacket/">
            <img width="350" height="350" src="./theme/images/product-71-350x350.jpg" class="attachment-shop_small wp-post-image" alt="product-7">
            <strong>Wool Blended Jacket</strong>
            <span class="price">£460.00</span>
        </a>
        <a href="http://alexgurghis.com/themes/zeux-ecommerce/?add-to-cart=658&_n=873fa40d2d" class="button" rel="nofollow">Add to cart</a>
    </li>

    <li class="product ">
        <a href="http://alexgurghis.com/themes/zeux-ecommerce/product/stretch-cotton-suit/">
            <img width="350" height="350" src="./theme/images/product-11-350x350.jpg" class="attachment-shop_small wp-post-image" alt="product-1">
            <strong>Stretch Cotton Suit</strong>
            <span class="price">£1,700.00</span>
        </a>
        <a href="http://alexgurghis.com/themes/zeux-ecommerce/product/stretch-cotton-suit/" class="button">Select</a>
    </li>	

    <li class="product ">
        <a href="http://alexgurghis.com/themes/zeux-ecommerce/product/cotton-jacket/">
            <span class="onsale">Sale!</span><img width="350" height="350" src="./theme/images/product-21-350x350.jpg" class="attachment-shop_small wp-post-image" alt="product-2">
            <strong>Cotton Jacket</strong>
            <span class="price">
                <del>£7,500.00</del>
                <ins>£5,600.00</ins>
            </span>
        </a>
        <a href="http://alexgurghis.com/themes/zeux-ecommerce/?add-to-cart=651&_n=873fa40d2d" class="button" rel="nofollow">Add to cart</a>
    </li>	

    <li class="product last">
        <a href="http://alexgurghis.com/themes/zeux-ecommerce/product/cotton-stripe/">
            <img width="350" height="350" src="./theme/images/product-31-350x350.jpg" class="attachment-shop_small wp-post-image" alt="product-3">
            <strong>Cotton Stripe</strong>
            <span class="price">£900.00</span>
        </a>
        <a href="http://alexgurghis.com/themes/zeux-ecommerce/?add-to-cart=648&_n=873fa40d2d" class="button" rel="nofollow">Add to cart</a>
    </li>	

    <li class="product first">
        <a href="http://alexgurghis.com/themes/zeux-ecommerce/product/cotton-blouson/">
            <span class="onsale">Sale!</span><img width="350" height="350" src="./theme/images/product-81-350x350.jpg" class="attachment-shop_small wp-post-image" alt="product-8">
            <strong>Cotton Blouson</strong>
            <span class="price">
                <del>£1,400.00</del>£1,190.00
                <br><ins>15% off!</ins>
            </span>
        </a>
        <a href="http://alexgurghis.com/themes/zeux-ecommerce/?add-to-cart=639&_n=873fa40d2d" class="button" rel="nofollow">Add to cart</a>
    </li>	

    <li class="product ">
        <a href="http://alexgurghis.com/themes/zeux-ecommerce/product/cotton-coat/">
            <img width="350" height="350" src="./theme/images/product-91-350x350.jpg" class="attachment-shop_small wp-post-image" alt="product-9">
            <strong>Cotton Coat</strong>
            <span class="price">£860.00</span>
        </a>
        <a href="http://alexgurghis.com/themes/zeux-ecommerce/?add-to-cart=637&_n=873fa40d2d" class="button" rel="nofollow">Add to cart</a>
    </li>	

    <li class="product ">
        <a href="http://alexgurghis.com/themes/zeux-ecommerce/product/linen-cotton-blouson/">
            <img width="350" height="350" src="./theme/images/product-101-350x350.jpg" class="attachment-shop_small wp-post-image" alt="product-10">
            <strong>Linen Cotton Blouson</strong>
            <span class="price">£900.00</span>
        </a>
        <a href="http://alexgurghis.com/themes/zeux-ecommerce/?add-to-cart=635&_n=873fa40d2d" class="button" rel="nofollow">Add to cart</a>
    </li>	

    <li class="product last">
        <a href="http://alexgurghis.com/themes/zeux-ecommerce/product/linen-jacket/">
            <img width="350" height="350" src="./theme/images/product-51-350x350.jpg" class="attachment-shop_small wp-post-image" alt="product-5">
            <strong>Linen Jacket</strong>
            <span class="price">£490.00</span>
        </a>
        <a href="http://alexgurghis.com/themes/zeux-ecommerce/?add-to-cart=630&_n=873fa40d2d" class="button" rel="nofollow">Add to cart</a>
    </li>
</ul>
