<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
    'AGAcl\Module'                          => __DIR__ . '/Module.php',
    'AGAcl\Fixture\LoadRole'                => __DIR__ . '/src/AGAcl/Fixture/LoadRole.php',
    'AGAcl\Fixture\LoadResource'            => __DIR__ . '/src/AGAcl/Fixture/LoadResource.php',
    'AGAcl\Fixture\LoadPrivilege'           => __DIR__ . '/src/AGAcl/Fixture/LoadPrivilege.php',
    'AGAcl\Form\Resource'                   => __DIR__ . '/src/AGAcl/Form/Resource.php',
    'AGAcl\Form\Privilege'                  => __DIR__ . '/src/AGAcl/Form/Privilege.php',
    'AGAcl\Form\Role'                       => __DIR__ . '/src/AGAcl/Form/Role.php',
    'AGAcl\Permissions\Acl'                 => __DIR__ . '/src/AGAcl/Permissions/Acl.php',
    'AGAcl\Controller\PrivilegesController' => __DIR__ . '/src/AGAcl/Controller/PrivilegesController.php',
    'AGAcl\Controller\RolesController'      => __DIR__ . '/src/AGAcl/Controller/RolesController.php',
    'AGAcl\Controller\ResourcesController'  => __DIR__ . '/src/AGAcl/Controller/ResourcesController.php',
    'AGAcl\Service\Resource'                => __DIR__ . '/src/AGAcl/Service/Resource.php',
    'AGAcl\Service\Privilege'               => __DIR__ . '/src/AGAcl/Service/Privilege.php',
    'AGAcl\Service\Role'                    => __DIR__ . '/src/AGAcl/Service/Role.php',
    'AGAcl\Repository\RoleRepository'       => __DIR__ . '/src/AGAcl/Repository/RoleRepository.php',
    'AGAcl\Repository\ResourceRepository'   => __DIR__ . '/src/AGAcl/Repository/ResourceRepository.php',
    'AGAcl\Repository\PrivilegeRepository'  => __DIR__ . '/src/AGAcl/Repository/PrivilegeRepository.php',
    'AGAcl\Entity\Resource'                 => __DIR__ . '/src/AGAcl/Entity/Resource.php',
    'AGAcl\Entity\Privilege'                => __DIR__ . '/src/AGAcl/Entity/Privilege.php',
    'AGAcl\Entity\Role'                     => __DIR__ . '/src/AGAcl/Entity/Role.php',
);
